version: '1.0'
stages:
  - checkout
  - build
  - push
  - test
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
  buildImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: "wawa-dt-poc"
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile
    disable_push: true
    registry: "wawa-dt-poc"
  pushImagesToECR:
    title: "Pushing image to ECR"
    stage: "push"
    type: "push"
    candidate: '${{buildImage}}'
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    registry: "wawa-dt-poc"
  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{main_clone}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"
  deploy:
    title: Deploy to EKS
    stage: "deploy"
    type: "freestyle"
    image: codefresh/cf-deploy-kubernetes:master
    commands:
      - /cf-deploy-kubernetes deployment-cf.yaml
    environment:
      - KUBECONTEXT=amazon_eks
      - KUBERNETES_NAMESPACE=nginx-ns
      - REPLICA_NUMBER=3
      - CONTAINER_PORT=80
      - SERVICE_PORT=80
      - TARGET_PORT=80
      - AWS_ACCOUNT=293313708031
      - AWS_REGION=us-east-1
      - REGISTRY_NAME=wawa-dt-poc
      - PULL_SECRET=codefresh-generated-293313708031.dkr.ecr.us-east-1.amazonaws.com-wawa-dt-poc-nginx-ns
