---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: {{REPLICA_NUMBER}}
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: {{AWS_ACCOUNT}}.dkr.ecr.{{AWS_REGION}}.amazonaws.com/{{REGISTRY_NAME}}:{{CF_BRANCH_TAG_NORMALIZED}}-{{CF_SHORT_REVISION}}
        ports:
        - containerPort: {{CONTAINER_PORT}}
